
CREATE TABLE wealth (
    market          text,
    date            date,
    cnt_price       integer,
    cnt_volume      integer,
    cnt_capital     integer,
    open_price      double precision,
    open_volume     double precision,
    open_capital    double precision,
    close_price     double precision,
    close_volume    double precision,
    close_capital   double precision,
    min_price       double precision,
    min_volume      double precision,
    min_capital     double precision,
    mean_price      double precision,
    mean_volume     double precision,
    mean_capital    double precision,
    max_price       double precision,
    max_volume      double precision,
    max_capital     double precision,
    std_price       double precision,
    std_volume      double precision,
    std_capital     double precision,
    PRIMARY KEY (market, date)
);
